name: Deploy to AWS (release)
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy
        run: aws s3 sync --delete --exclude=beta/\* --content-encoding utf8 _site s3://n2g.claude-apps.com/website/
